// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type BoolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResult) Reset() {
	*x = BoolResult{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResult) ProtoMessage() {}

func (x *BoolResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResult.ProtoReflect.Descriptor instead.
func (*BoolResult) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *BoolResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BoolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "info" | "warn" | "error"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ConfigGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetRequest) Reset() {
	*x = ConfigGetRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetRequest) ProtoMessage() {}

func (x *ConfigGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetRequest.ProtoReflect.Descriptor instead.
func (*ConfigGetRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ConfigGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetResponse) Reset() {
	*x = ConfigGetResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetResponse) ProtoMessage() {}

func (x *ConfigGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigGetResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigGetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type RegisterRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`         // "GET" | "POST" | "PUT" | "DELETE"
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`             // "/stats" (自动加前缀 /v1/plugin/{name})
	Handler       string                 `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`       // WASM 导出函数名
	Middleware    []string               `protobuf:"bytes,4,rep,name=middleware,proto3" json:"middleware,omitempty"` // "auth" | "device" | 自定义中间件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRouteRequest) Reset() {
	*x = RegisterRouteRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRouteRequest) ProtoMessage() {}

func (x *RegisterRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRouteRequest.ProtoReflect.Descriptor instead.
func (*RegisterRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRouteRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RegisterRouteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterRouteRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *RegisterRouteRequest) GetMiddleware() []string {
	if x != nil {
		return x.Middleware
	}
	return nil
}

type RegisterMiddlewareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 中间件名，供路由引用
	Handler       string                 `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"` // WASM 导出函数名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMiddlewareRequest) Reset() {
	*x = RegisterMiddlewareRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMiddlewareRequest) ProtoMessage() {}

func (x *RegisterMiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMiddlewareRequest.ProtoReflect.Descriptor instead.
func (*RegisterMiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterMiddlewareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterMiddlewareRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

type MiddlewareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                                                             // "next" | "abort" | "modify"
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                                                                            // for abort
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // for abort
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // headers to add (for next/modify) or return (for abort)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareResponse) Reset() {
	*x = MiddlewareResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareResponse) ProtoMessage() {}

func (x *MiddlewareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareResponse.ProtoReflect.Descriptor instead.
func (*MiddlewareResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *MiddlewareResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MiddlewareResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MiddlewareResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MiddlewareResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type EnqueueTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"` // asynq task type name
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                   // task payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueTaskRequest) Reset() {
	*x = EnqueueTaskRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTaskRequest) ProtoMessage() {}

func (x *EnqueueTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTaskRequest.ProtoReflect.Descriptor instead.
func (*EnqueueTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *EnqueueTaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *EnqueueTaskRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DbQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`           // "user" | "order" | "subscribe" | ...
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`   // "find" | "list" | "create" | "update" | "delete"
	Conditions    *structpb.Struct       `protobuf:"bytes,3,opt,name=conditions,proto3" json:"conditions,omitempty"` // 动态条件
	Fields        *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`         // 指定返回字段
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbQueryRequest) Reset() {
	*x = DbQueryRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbQueryRequest) ProtoMessage() {}

func (x *DbQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbQueryRequest.ProtoReflect.Descriptor instead.
func (*DbQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *DbQueryRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DbQueryRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DbQueryRequest) GetConditions() *structpb.Struct {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *DbQueryRequest) GetFields() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DbQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DbQueryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DbQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*structpb.Struct     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbQueryResponse) Reset() {
	*x = DbQueryResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbQueryResponse) ProtoMessage() {}

func (x *DbQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbQueryResponse.ProtoReflect.Descriptor instead.
func (*DbQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *DbQueryResponse) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DbQueryResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DbQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RedisGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisGetRequest) Reset() {
	*x = RedisGetRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisGetRequest) ProtoMessage() {}

func (x *RedisGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisGetRequest.ProtoReflect.Descriptor instead.
func (*RedisGetRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *RedisGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RedisGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisGetResponse) Reset() {
	*x = RedisGetResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisGetResponse) ProtoMessage() {}

func (x *RedisGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisGetResponse.ProtoReflect.Descriptor instead.
func (*RedisGetResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *RedisGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RedisGetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type RedisSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisSetRequest) Reset() {
	*x = RedisSetRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisSetRequest) ProtoMessage() {}

func (x *RedisSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisSetRequest.ProtoReflect.Descriptor instead.
func (*RedisSetRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *RedisSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RedisSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RedisSetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type EmitEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventRequest) Reset() {
	*x = EmitEventRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventRequest) ProtoMessage() {}

func (x *EmitEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventRequest.ProtoReflect.Descriptor instead.
func (*EmitEventRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *EmitEventRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *EmitEventRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SubscribeEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`     // event name, "*" means all events
	Handler       string                 `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"` // WASM export name, default: on_<event>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventRequest) Reset() {
	*x = SubscribeEventRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventRequest) ProtoMessage() {}

func (x *SubscribeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *SubscribeEventRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *SubscribeEventRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

type HttpRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequestRequest) Reset() {
	*x = HttpRequestRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequestRequest) ProtoMessage() {}

func (x *HttpRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequestRequest.ProtoReflect.Descriptor instead.
func (*HttpRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *HttpRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequestRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpRequestRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequestRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequestResponse) Reset() {
	*x = HttpRequestResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequestResponse) ProtoMessage() {}

func (x *HttpRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequestResponse.ProtoReflect.Descriptor instead.
func (*HttpRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *HttpRequestResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpRequestResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequestResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ScheduleTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cron          string                 `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"`       // "0 */6 * * *"
	Handler       string                 `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"` // WASM 导出函数名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskRequest) Reset() {
	*x = ScheduleTaskRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskRequest) ProtoMessage() {}

func (x *ScheduleTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ScheduleTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleTaskRequest) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *ScheduleTaskRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // 插件专属配置
	HostConfig    *HostConfig            `protobuf:"bytes,3,opt,name=host_config,json=hostConfig,proto3" json:"host_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *InitRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InitRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitRequest) GetHostConfig() *HostConfig {
	if x != nil {
		return x.HostConfig
	}
	return nil
}

type HostConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SiteName       string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	SiteHost       string                 `protobuf:"bytes,2,opt,name=site_host,json=siteHost,proto3" json:"site_host,omitempty"`
	CurrencyUnit   string                 `protobuf:"bytes,3,opt,name=currency_unit,json=currencyUnit,proto3" json:"currency_unit,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,4,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	Debug          bool                   `protobuf:"varint,5,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostConfig) Reset() {
	*x = HostConfig{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostConfig) ProtoMessage() {}

func (x *HostConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostConfig.ProtoReflect.Descriptor instead.
func (*HostConfig) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *HostConfig) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *HostConfig) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

func (x *HostConfig) GetCurrencyUnit() string {
	if x != nil {
		return x.CurrencyUnit
	}
	return ""
}

func (x *HostConfig) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *HostConfig) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type HandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         map[string]*StringList `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]*StringList `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Context       *RequestContext        `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *HandleRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HandleRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HandleRequest) GetQuery() map[string]*StringList {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *HandleRequest) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HandleRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *RequestContext) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RequestContext) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *RequestContext) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type HandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *HandleResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type AsyncSubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpType        string                 `protobuf:"bytes,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"` // "http_get", "http_post", "db_query", "redis_get", "redis_set"
	Params        []byte                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`               // protobuf-encoded request (HttpRequestRequest, RedisGetRequest, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncSubmitRequest) Reset() {
	*x = AsyncSubmitRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncSubmitRequest) ProtoMessage() {}

func (x *AsyncSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncSubmitRequest.ProtoReflect.Descriptor instead.
func (*AsyncSubmitRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *AsyncSubmitRequest) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *AsyncSubmitRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type AsyncSubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncSubmitResponse) Reset() {
	*x = AsyncSubmitResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncSubmitResponse) ProtoMessage() {}

func (x *AsyncSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncSubmitResponse.ProtoReflect.Descriptor instead.
func (*AsyncSubmitResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *AsyncSubmitResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type AsyncResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncResolveRequest) Reset() {
	*x = AsyncResolveRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncResolveRequest) ProtoMessage() {}

func (x *AsyncResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncResolveRequest.ProtoReflect.Descriptor instead.
func (*AsyncResolveRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *AsyncResolveRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type AsyncResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // protobuf-encoded response (HttpRequestResponse, RedisGetResponse, etc.)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncResolveResponse) Reset() {
	*x = AsyncResolveResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncResolveResponse) ProtoMessage() {}

func (x *AsyncResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncResolveResponse.ProtoReflect.Descriptor instead.
func (*AsyncResolveResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *AsyncResolveResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *AsyncResolveResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *AsyncResolveResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AsyncResolveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AsyncWaitAnyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncWaitAnyRequest) Reset() {
	*x = AsyncWaitAnyRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncWaitAnyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncWaitAnyRequest) ProtoMessage() {}

func (x *AsyncWaitAnyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncWaitAnyRequest.ProtoReflect.Descriptor instead.
func (*AsyncWaitAnyRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{29}
}

type AsyncWaitAnyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // the task that completed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncWaitAnyResponse) Reset() {
	*x = AsyncWaitAnyResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncWaitAnyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncWaitAnyResponse) ProtoMessage() {}

func (x *AsyncWaitAnyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncWaitAnyResponse.ProtoReflect.Descriptor instead.
func (*AsyncWaitAnyResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *AsyncWaitAnyResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

var File_api_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_api_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/plugin/v1/plugin.proto\x12\x10ppanel.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/field_mask.proto\"\a\n" +
	"\x05Empty\"<\n" +
	"\n" +
	"BoolResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb9\x01\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\x06fields\x18\x03 \x03(\v2(.ppanel.plugin.v1.LogRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x10ConfigGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"A\n" +
	"\x11ConfigGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"|\n" +
	"\x14RegisterRouteRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\ahandler\x18\x03 \x01(\tR\ahandler\x12\x1e\n" +
	"\n" +
	"middleware\x18\x04 \x03(\tR\n" +
	"middleware\"I\n" +
	"\x19RegisterMiddlewareRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\"\xe1\x01\n" +
	"\x12MiddlewareResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12K\n" +
	"\aheaders\x18\x04 \x03(\v21.ppanel.plugin.v1.MiddlewareResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x12EnqueueTaskRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\"\xdf\x01\n" +
	"\x0eDbQueryRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x127\n" +
	"\n" +
	"conditions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"conditions\x122\n" +
	"\x06fields\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\x06fields\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"j\n" +
	"\x0fDbQueryResponse\x12+\n" +
	"\x04rows\x18\x01 \x03(\v2\x17.google.protobuf.StructR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"#\n" +
	"\x0fRedisGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"@\n" +
	"\x10RedisGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"Z\n" +
	"\x0fRedisSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"[\n" +
	"\x10EmitEventRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\"G\n" +
	"\x15SubscribeEventRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\"\xdb\x01\n" +
	"\x12HttpRequestRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12K\n" +
	"\aheaders\x18\x03 \x03(\v21.ppanel.plugin.v1.HttpRequestRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x13HttpRequestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12L\n" +
	"\aheaders\x18\x03 \x03(\v22.ppanel.plugin.v1.HttpRequestResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x13ScheduleTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cron\x18\x02 \x01(\tR\x04cron\x12\x18\n" +
	"\ahandler\x18\x03 \x01(\tR\ahandler\"\x9e\x01\n" +
	"\vInitRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12=\n" +
	"\vhost_config\x18\x03 \x01(\v2\x1c.ppanel.plugin.v1.HostConfigR\n" +
	"hostConfig\"\xaa\x01\n" +
	"\n" +
	"HostConfig\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12\x1b\n" +
	"\tsite_host\x18\x02 \x01(\tR\bsiteHost\x12#\n" +
	"\rcurrency_unit\x18\x03 \x01(\tR\fcurrencyUnit\x12'\n" +
	"\x0fcurrency_symbol\x18\x04 \x01(\tR\x0ecurrencySymbol\x12\x14\n" +
	"\x05debug\x18\x05 \x01(\bR\x05debug\"\xc7\x03\n" +
	"\rHandleRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12@\n" +
	"\x05query\x18\x03 \x03(\v2*.ppanel.plugin.v1.HandleRequest.QueryEntryR\x05query\x12F\n" +
	"\aheaders\x18\x04 \x03(\v2,.ppanel.plugin.v1.HandleRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12:\n" +
	"\acontext\x18\x06 \x01(\v2 .ppanel.plugin.v1.RequestContextR\acontext\x1aV\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.ppanel.plugin.v1.StringListR\x05value:\x028\x01\x1aX\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.ppanel.plugin.v1.StringListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"a\n" +
	"\x0eRequestContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\"\xc1\x01\n" +
	"\x0eHandleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12G\n" +
	"\aheaders\x18\x03 \x03(\v2-.ppanel.plugin.v1.HandleResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x12AsyncSubmitRequest\x12\x17\n" +
	"\aop_type\x18\x01 \x01(\tR\x06opType\x12\x16\n" +
	"\x06params\x18\x02 \x01(\fR\x06params\".\n" +
	"\x13AsyncSubmitResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\".\n" +
	"\x13AsyncResolveRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"q\n" +
	"\x14AsyncResolveResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x15\n" +
	"\x13AsyncWaitAnyRequest\"/\n" +
	"\x14AsyncWaitAnyResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskIdB8Z6github.com/perfect-panel/server/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_api_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_api_plugin_v1_plugin_proto_rawDescData []byte
)

func file_api_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_api_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_api_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_plugin_v1_plugin_proto_rawDesc), len(file_api_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_api_plugin_v1_plugin_proto_rawDescData
}

var file_api_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_api_plugin_v1_plugin_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: ppanel.plugin.v1.Empty
	(*BoolResult)(nil),                // 1: ppanel.plugin.v1.BoolResult
	(*LogRequest)(nil),                // 2: ppanel.plugin.v1.LogRequest
	(*ConfigGetRequest)(nil),          // 3: ppanel.plugin.v1.ConfigGetRequest
	(*ConfigGetResponse)(nil),         // 4: ppanel.plugin.v1.ConfigGetResponse
	(*RegisterRouteRequest)(nil),      // 5: ppanel.plugin.v1.RegisterRouteRequest
	(*RegisterMiddlewareRequest)(nil), // 6: ppanel.plugin.v1.RegisterMiddlewareRequest
	(*MiddlewareResponse)(nil),        // 7: ppanel.plugin.v1.MiddlewareResponse
	(*EnqueueTaskRequest)(nil),        // 8: ppanel.plugin.v1.EnqueueTaskRequest
	(*DbQueryRequest)(nil),            // 9: ppanel.plugin.v1.DbQueryRequest
	(*DbQueryResponse)(nil),           // 10: ppanel.plugin.v1.DbQueryResponse
	(*RedisGetRequest)(nil),           // 11: ppanel.plugin.v1.RedisGetRequest
	(*RedisGetResponse)(nil),          // 12: ppanel.plugin.v1.RedisGetResponse
	(*RedisSetRequest)(nil),           // 13: ppanel.plugin.v1.RedisSetRequest
	(*EmitEventRequest)(nil),          // 14: ppanel.plugin.v1.EmitEventRequest
	(*SubscribeEventRequest)(nil),     // 15: ppanel.plugin.v1.SubscribeEventRequest
	(*HttpRequestRequest)(nil),        // 16: ppanel.plugin.v1.HttpRequestRequest
	(*HttpRequestResponse)(nil),       // 17: ppanel.plugin.v1.HttpRequestResponse
	(*ScheduleTaskRequest)(nil),       // 18: ppanel.plugin.v1.ScheduleTaskRequest
	(*InitRequest)(nil),               // 19: ppanel.plugin.v1.InitRequest
	(*HostConfig)(nil),                // 20: ppanel.plugin.v1.HostConfig
	(*HandleRequest)(nil),             // 21: ppanel.plugin.v1.HandleRequest
	(*StringList)(nil),                // 22: ppanel.plugin.v1.StringList
	(*RequestContext)(nil),            // 23: ppanel.plugin.v1.RequestContext
	(*HandleResponse)(nil),            // 24: ppanel.plugin.v1.HandleResponse
	(*AsyncSubmitRequest)(nil),        // 25: ppanel.plugin.v1.AsyncSubmitRequest
	(*AsyncSubmitResponse)(nil),       // 26: ppanel.plugin.v1.AsyncSubmitResponse
	(*AsyncResolveRequest)(nil),       // 27: ppanel.plugin.v1.AsyncResolveRequest
	(*AsyncResolveResponse)(nil),      // 28: ppanel.plugin.v1.AsyncResolveResponse
	(*AsyncWaitAnyRequest)(nil),       // 29: ppanel.plugin.v1.AsyncWaitAnyRequest
	(*AsyncWaitAnyResponse)(nil),      // 30: ppanel.plugin.v1.AsyncWaitAnyResponse
	nil,                               // 31: ppanel.plugin.v1.LogRequest.FieldsEntry
	nil,                               // 32: ppanel.plugin.v1.MiddlewareResponse.HeadersEntry
	nil,                               // 33: ppanel.plugin.v1.HttpRequestRequest.HeadersEntry
	nil,                               // 34: ppanel.plugin.v1.HttpRequestResponse.HeadersEntry
	nil,                               // 35: ppanel.plugin.v1.HandleRequest.QueryEntry
	nil,                               // 36: ppanel.plugin.v1.HandleRequest.HeadersEntry
	nil,                               // 37: ppanel.plugin.v1.HandleResponse.HeadersEntry
	(*structpb.Struct)(nil),           // 38: google.protobuf.Struct
	(*fieldmaskpb.FieldMask)(nil),     // 39: google.protobuf.FieldMask
}
var file_api_plugin_v1_plugin_proto_depIdxs = []int32{
	31, // 0: ppanel.plugin.v1.LogRequest.fields:type_name -> ppanel.plugin.v1.LogRequest.FieldsEntry
	32, // 1: ppanel.plugin.v1.MiddlewareResponse.headers:type_name -> ppanel.plugin.v1.MiddlewareResponse.HeadersEntry
	38, // 2: ppanel.plugin.v1.EnqueueTaskRequest.payload:type_name -> google.protobuf.Struct
	38, // 3: ppanel.plugin.v1.DbQueryRequest.conditions:type_name -> google.protobuf.Struct
	39, // 4: ppanel.plugin.v1.DbQueryRequest.fields:type_name -> google.protobuf.FieldMask
	38, // 5: ppanel.plugin.v1.DbQueryResponse.rows:type_name -> google.protobuf.Struct
	38, // 6: ppanel.plugin.v1.EmitEventRequest.payload:type_name -> google.protobuf.Struct
	33, // 7: ppanel.plugin.v1.HttpRequestRequest.headers:type_name -> ppanel.plugin.v1.HttpRequestRequest.HeadersEntry
	34, // 8: ppanel.plugin.v1.HttpRequestResponse.headers:type_name -> ppanel.plugin.v1.HttpRequestResponse.HeadersEntry
	38, // 9: ppanel.plugin.v1.InitRequest.config:type_name -> google.protobuf.Struct
	20, // 10: ppanel.plugin.v1.InitRequest.host_config:type_name -> ppanel.plugin.v1.HostConfig
	35, // 11: ppanel.plugin.v1.HandleRequest.query:type_name -> ppanel.plugin.v1.HandleRequest.QueryEntry
	36, // 12: ppanel.plugin.v1.HandleRequest.headers:type_name -> ppanel.plugin.v1.HandleRequest.HeadersEntry
	23, // 13: ppanel.plugin.v1.HandleRequest.context:type_name -> ppanel.plugin.v1.RequestContext
	37, // 14: ppanel.plugin.v1.HandleResponse.headers:type_name -> ppanel.plugin.v1.HandleResponse.HeadersEntry
	22, // 15: ppanel.plugin.v1.HandleRequest.QueryEntry.value:type_name -> ppanel.plugin.v1.StringList
	22, // 16: ppanel.plugin.v1.HandleRequest.HeadersEntry.value:type_name -> ppanel.plugin.v1.StringList
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_plugin_v1_plugin_proto_init() }
func file_api_plugin_v1_plugin_proto_init() {
	if File_api_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugin_v1_plugin_proto_rawDesc), len(file_api_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_api_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_api_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_api_plugin_v1_plugin_proto = out.File
	file_api_plugin_v1_plugin_proto_goTypes = nil
	file_api_plugin_v1_plugin_proto_depIdxs = nil
}
